# Tutorial: introduction to <font color='#1F618D'>Python</font>

###   Properties

- is a high-level, dynamically typed multiparadigm programming language. 
- its code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

Example: Simplicity of Python code

In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


### Python versions
There are currently two different supported versions of Python, 2 and 3. 
For this class, the code will be in Python 3.7 and compatible with >= 3.6.

You can check your Python version at the command line by running `python --version`.

### Basic data types
- Numeric:
    - Integer (Positive or negative whole numbers; without a fractional part)
    - Float (Any real number with a floating point representation in which a fractional component)

- Boolean (Data with one of two built-in values True or False) 

- String (a collection of one or more characters put in single, double or triple quotes)

- Container Type
    - List (an ordered collection of one or more data items, not necessarily of the same type, written with square brackets)
    - Dictionary (an unordered collection of data in a key:value pair form)
    - Set (an unordered collection; written with curly brackets)
    - Tuple (an ordered collection of one or more data items, not necessarily of the same type, written with parentheses)

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-complex).

**Numeric types:** Integer and Float 

In [2]:
x = 3
print(x)
print(type(x)) 

print("\n"*2)  # linebreak/newline character

y= 4.6
print(y)
print(type(y)) 

print(x * 2)

3
<class 'int'>



4.6
<class 'float'>
6


**Booleans**: 
- Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.)

In [3]:
t = True
f = False

print(t or f)  # Logical OR; prints "True"

print(not t)   # Logical NOT; prints "False"

print(t != f)  # Logical XOR; prints "True"

True
False
True


**Strings**: Python has great support for strings:

In [4]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.

print(len(hello))  # String length; prints "5"

hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"



int_num = 12
float_num = 4.5436


str_fmt = '%s %i %0.2f' % (hello, int_num, float_num)  # “Old Style” String Formatting (%: String Modulo Operator)
print(str_fmt)  # prints "hello world 12"


str_fmt = 'hello {} {} {:0.2f}'.format(world, int_num, float_num) # “New Style” String Formatting (str.format)
print(str_fmt) 


str_fmt = f'{hello} {int_num} {float_num:0.2f}' # f-strings, a new and improved way of formatting strings, available in python >= 3.6
print(str_fmt)

5
hello world
hello 12 4.54
hello world 12 4.54
hello 12 4.54


- String objects have a bunch of useful methods; for example:

In [5]:
s = "data mining"

print(s.capitalize())  # Capitalize a string; prints "Data mining"

print(s.upper())       # Convert a string to uppercase; prints "DATA MINING"

print(s.replace('data', 'data stream'))  # Replace all instances of one substring with another

print('  data  '.strip())  # Strip/remove leading and trailing whitespace; prints "data"

print(s.split(" "))

Data mining
DATA MINING
data stream mining
data
['data', 'mining']


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### Containers
Python includes several built-in container types: **list**, **dictionary**, **set**, and **tuple**.

### List
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [6]:
xs = [3, 1, 4]  

print(xs[2])      # index start from '0′
print(xs[-1])     # Negative indices count from the end of the list; prints "4"

xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)

xs.append('bar')  # Add a new element to the end of the list
print(xs)


print(xs.index(3)) # prints 0


x = xs.pop()      # Remove and return the last element of the list
print(f"'{x}'", "has been removed from the list")
print("Now, the list is ", xs)


xs.remove('foo') # removes the first instance of a value in a list
print(xs)

del xs[0]   # equivalent to list.remove(), but it does not return the removed element
print(xs)




4
4
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
0
'bar' has been removed from the list
Now, the list is  [3, 1, 'foo']
[3, 1]
[1]


- You can find all the details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

**Slicing**:
- In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [7]:
nums = list(range(5))     # range is a built-in function that creates a sequence of numbers
print(nums)               # Prints "[0, 1, 2, 3, 4]"


print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"

print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"

print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"

print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"

print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"

nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


We will see slicing again in the context of numpy arrays.

**Loops**: You can loop over the elements of a list like this:

In [8]:
animals = ['cat', 'dog', 'monkey']

for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [9]:
animals = ['cat', 'dog', 'monkey']

for idx, animal in enumerate(animals):
    print(f'#{idx +1}: {animal}')

#1: cat
#2: dog
#3: monkey


**List comprehensions**: List comprehensions offer a simple way to create lists based on existing lists.

In [10]:
nums = [0, 1, 2, 3, 4]
squares = []

for x in nums:
    squares.append(x ** 2)  # The ** operator in Python is used to raise the number on the left to the power of the exponent of the right
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


You can make this code simpler using a **list comprehension**:

In [11]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [12]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


### <font color='#3498DB'>Question 1:</font> 
### Express the following Python "For loop" code using list comprehension

In [13]:
result = []
for x in range(10):
    if x % 2 == 0:
        for y in range(10):
            if y % 2 == 1:
                result.append((x,y))
                
print(result)

[(0, 1), (0, 3), (0, 5), (0, 7), (0, 9), (2, 1), (2, 3), (2, 5), (2, 7), (2, 9), (4, 1), (4, 3), (4, 5), (4, 7), (4, 9), (6, 1), (6, 3), (6, 5), (6, 7), (6, 9), (8, 1), (8, 3), (8, 5), (8, 7), (8, 9)]


### Dictionary
- a flexibly sized collection of key-value pairs, where key and value are Python objects
- one approach for creating a dictionary is to use curly braces {} and colons to separate keys and values

In [14]:

d = {'cat': 'cute',
     'dog': 'furry'}  # Create a new dictionary with some data

print(d['cat'])       # Get an entry from a dictionary; prints "cute"

print('cat' in d)     # Check if a dictionary has a given key; prints "True"


d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"


print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"

del d['fish']         # Remove an element from a dictionary

print(d)

cute
True
wet
N/A
{'cat': 'cute', 'dog': 'furry'}


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#dict).

**Loops**: It is easy to iterate over the keys in a dictionary:

In [15]:
d = {'dog': 4,
     'spider': 8,
     'cat': 4}

for animal in d:
    legs = d[animal]
    print(f'A {animal} has {legs} legs')


A dog has 4 legs
A spider has 8 legs
A cat has 4 legs


If you want to access to keys and their corresponding values, use the **items()** method:

- dicts.items()

In [16]:
d = {'dog': 4,
     'spider': 8,
     'cat': 4}

for animal, legs in d.items():
    print(f'A {animal} has {legs} legs')


A dog has 4 legs
A spider has 8 legs
A cat has 4 legs


If you want to get the keys or values, use the **keys()** and **values()**, respectively:

- dicts.keys()
- dicts.values()

In [17]:
print(d.items())

print(d.keys())

print(d.values())

dict_items([('dog', 4), ('spider', 8), ('cat', 4)])
dict_keys(['dog', 'spider', 'cat'])
dict_values([4, 8, 4])


In [18]:
sorted(d.items(), key=lambda kv: kv[0], reverse=False) # sorting by key

[('cat', 4), ('dog', 4), ('spider', 8)]

In [19]:
sorted(d.items(), key=lambda kv: kv[1], reverse=False) # sorting by value

[('dog', 4), ('cat', 4), ('spider', 8)]

**Dictionary comprehensions**: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [20]:
nums = [0, 1, 2, 3, 4]

even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


### Set
- an unordered collection of unique elements. 
- you can think of them like dicts, but keys only, no values.

In [21]:
animals = {'cat', 'dog'}

print('cat' in animals)   # prints "True"

animals.add('fish')       # Add an element to a set

print(len(animals))       # Number of elements in a set; prints "3"

animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
3
2


Everything you want to know about sets can be found in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#set).

**Loops**: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [22]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(f'#{idx +1}: {animal}') # Prints items in some undefined order

#1: cat
#2: fish
#3: dog


**Set comprehensions**: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [23]:
from math import sqrt

nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


#### Tuples
- A tuple is a fixed-length, immutable sequence of Python objects. The easiest way to create one is with a comma-separated sequence of values (or in parentheses)
- a tuple is an (immutable) ordered list of values. 
- one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example


In [24]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


### ZIP function

- "zip" function pairs up the elements of a number of lists, tuples, or other sequences to create a list of tuples

In [25]:
numbers = [1, 2, 3]
letters = ['a', 'b', 'c']

zipped = zip(numbers, letters)

print(zipped)
print(list(zipped))

[(1, 'a'), (2, 'b'), (3, 'c')]


The [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#tuples-and-sequences) has more information about tuples.

Python uses whitespace (tabs or spaces) to structure code instead of using braces as in
many other languages like C++ and Java.

### Functions
Python functions are defined using the `def` keyword. For example:

In [26]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))            # Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [27]:
def hello(name, loud=False):
    if loud:
        print(f'HELLO, {name.upper()}!')
    else:
        print(f'Hello, {name}')

hello('Alex')             # Prints "Hello, Alex"
hello('Alex', loud=True)  # Prints "HELLO, ALEX!"

Hello, Alex
HELLO, ALEX!


### Anonymous (Lambda) Functions

- anonymous or lambda functions are a way of writing functions consisting of a single statement, the result of which is the return value
- defined by the **lambda** keyword

In [28]:
def calc_func(x):
    return x * 2

print(calc_func(3))

6


In [29]:
equiv_lambda_func = lambda x: x * 2

print(equiv_lambda_func(3))

6


In [30]:
numbers = [1, 2, 3, 4]

list(map(lambda x: x*x, numbers))

[1, 4, 9, 16]

There is a lot more information about Python functions in the [documentation](https://docs.python.org/3.7/tutorial/controlflow.html#defining-functions).

### Classes
- In object-oriented programming, a class is an extensible program-code-template for creating objects, providing:
     - initial values for state (member variables) and implementations of behavior (member functions or methods)
     - he syntax for defining classes in Python is straightforward:

In [31]:
class Person:
    # Constructor
  def __init__(self, name):
    self.name = name


  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("Alex")        # This constructs an instance of the Person class
p1.myfunc()                # This calls an instance method

Hello my name is Alex


You can read a lot more about Python classes in the [documentation](https://docs.python.org/3.7/tutorial/classes.html).

# <font color='#1F618D'>NumPy (Numerical Python)</font>

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

Let's import `numpy`. we usually import it using the **alias** `np`:

In [32]:
import numpy as np

### Arrays

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.

A numpy array
- is a grid of values, all of the same type 
- is indexed by a tuple of nonnegative integers 

The number of dimensions is the **rank** of the array

The **shape** of an array is a tuple of integers giving the size of the array along each dimension.

<div>
<img src="./pic1.png" width="500"/>
</div>

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [33]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"

print(a.shape)            # Prints "(3,)"
print(a.ndim)             # Prints "1"


print(a[1])               # Prints "1 2 3"

a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],
              [4,5,6]])   # Create a rank 2 array

print(b.shape)            # Prints "(2, 3)"

print(b.ndim)             # Prints "2"


print(b[0, 1])            # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1
2
[5 2 3]
(2, 3)
2
2


Numpy also provides many functions to create arrays:

In [34]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

bb = np.ones_like(a)


c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
    
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98631289 0.53382335]
 [0.54154681 0.41680851]]


- ones_like
- zeros_like
- empty_like
- full_like

In [35]:
a = np.full((3,4), 7) 

b = np.zeros_like(a)  # equivalent to np.ones(a.shape)

print(a)
print(b)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


You can read about other methods of array creation in the [documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

#### Data Types for ndarrays


In [36]:
arr = np.array([1, 2, 3], dtype=np.int32)

print(arr.dtype)

int32


- You can explicitly convert or cast an array from one dtype to another using ndarray’s **astype** method

### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [37]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [38]:
float_arr = arr.astype(np.float32)

print(float_arr.dtype)


numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

float32


array([ 1.25, -9.6 , 42.  ])

### Arithmetic with NumPy Arrays
- NumPy arrays enable you to express batch operations on data without writing any 'for' loops
- NumPy users call this vectorization

Any arithmetic operations between equal-size arrays applies the operation element-wise

In [39]:
arr1 = np.array([[1., 2., 3.], 
                [4., 5., 6.]])

arr2 = np.array([[1., 2., 3.], 
                [4., 5., 6.]])

arr_mul = arr1 * arr2
print(arr_mul, '\n'*2)


arr_add = arr1 + arr2
print(arr_add)

[[ 1.  4.  9.]
 [16. 25. 36.]] 


[[ 2.  4.  6.]
 [ 8. 10. 12.]]


### Array Indexing
Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

### Two-dimensional array slicing

<div>
<img src="./pic3.png" width="800"/>
</div>

- An important first distinction from Python’s built-in lists is that array slices are **views** on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [40]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])


b = a[:2, 1:3]
print(b)            # prints:
                    # [[2 3]
                    # [6 7]]


b[0, 0] = 77        # b[0, 0] is the same piece of data as a[0, 1]
print(b)

print(a)   



row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[[2 3]
 [6 7]]
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


- If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array
     - for example: new_arr = arr[5:8].copy() .

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [41]:
# Create a new array from which we will select elements
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12]])

print(a, "\n"*2)


# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of 'a' using the indices in b
print(a[np.arange(4), b], "\n"*2)  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 


[ 1  6  7 11] 


[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. This type of indexing is used to select the elements of an array that satisfy some condition.

In [42]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


#### NumPy Sort

In [43]:
arr = np.random.randn(6)



arr_sorted = np.sort(arr)
print(arr_sorted)

[-1.97344328 -0.1172469   0.37032555  0.98366486  1.3547305   1.94809563]


#### NumPy Unique

In [44]:
arr = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

print(np.unique(arr))

[1 2 3 4]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

#### NumPy Where

In [45]:
x = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
condition = np.array([True, False, True, True, False])


result = np.where(condition, x, y)

print(result)


print(np.argwhere(condition))

[1.1 2.2 1.3 1.4 2.5]
[[0]
 [2]
 [3]]


### <font color='#3498DB'>Question 2:</font> 
### Express the Python "NumPy where" example above using list comprehension

### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [46]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [48]:
x = np.array([[1,2],
              [3,4]])

print(np.sum(x))          # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [49]:
x = np.array([[1,2], [3,4]])

print(x)    # Prints "[[1 2]
            #          [3 4]]"
    
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:

v = np.array([1,2,3])

print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Numpy provides many more functions for manipulating arrays; you can see the full list in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

### Numpy Documentation
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.